version: '3'

tasks:
  install:
    cmds:
      - pnpm install
      - pnpm prune

  build:
    deps: [ install ]
    cmds:
      - pnpm build

  run:
    deps: [ install ]
    cmds:
      - pnpm run dev

  #deploy:
  #  deps: [ build ]
  #  cmds:
  #    - rm -rf node_modules/.cache/gh-pages
  #    - npm run deploy
